-- CreateTable
CREATE TABLE `medias` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `etag` VARCHAR(191) NOT NULL,
    `server_side_encryption` VARCHAR(191) NOT NULL,
    `location` VARCHAR(191) NOT NULL,
    `key` VARCHAR(191) NOT NULL,
    `bucket` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
